-- Ejecuta este script en el editor SQL de tu proyecto en Supabase (app.supabase.com)
-- para crear la tabla que manejará el blog/noticias.

CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  excerpt TEXT,
  content TEXT NOT NULL,
  image_url TEXT,
  published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Configurar permisos de seguridad básicos (RLS)
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;

-- Cualquiera puede leer los posts (acceso público para la web)
CREATE POLICY "Permitir lectura publica de posts" 
ON posts FOR SELECT 
USING (true);

-- IMPORTANTE: Para este ejemplo básico, permitiremos operaciones de escritura anónimas.
-- En un entorno de producción estricto, debes vincular esto a Supabase Auth.
CREATE POLICY "Permitir insercion anonima" ON posts FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualizacion anonima" ON posts FOR UPDATE USING (true);
CREATE POLICY "Permitir borrado anonimo" ON posts FOR DELETE USING (true);

-- ==========================================
-- TABLA DE SERVICIOS Y HORARIOS
-- ==========================================

CREATE TABLE servicios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  icon TEXT,
  description TEXT,
  dias TEXT,
  horas TEXT,
  dias_tarde TEXT,
  horas_tarde TEXT,
  nota TEXT,
  is_active BOOLEAN DEFAULT true,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Configurar permisos de seguridad básicos (RLS)
ALTER TABLE servicios ENABLE ROW LEVEL SECURITY;

-- Cualquiera puede-- Policies para permitir acceso público de lectura
CREATE POLICY "Servicios visibles para todos" ON servicios
  FOR SELECT USING (true);

-- Tabla para configuraciones y textos de la marca blanca
CREATE TABLE IF NOT EXISTS configuraciones (
  clave text PRIMARY KEY,
  valor text NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS en configuraciones
ALTER TABLE configuraciones ENABLE ROW LEVEL SECURITY;

-- Policies para permitir acceso público de lectura
CREATE POLICY "Configuraciones visibles para todos" ON configuraciones
  FOR SELECT USING (true);

-- Insertar valores por defecto (Marca Blanca)
INSERT INTO configuraciones (clave, valor) VALUES 
(
  'instrucciones_cita',
  'Las citas para las especialidades se pueden tomar de lunes a jueves, en el horario de 8:00 a.m. a 11:00 a.m. y de 2:00 p.m. a 5:00 p.m.

Para tomar una cita, los pacientes deben dirigirse presencialmente a la institución dentro de los días y horarios especificados.'
),
('footer_ubicacion_texto', 'Sector Gulf, Guanire, Puerto La Cruz.'),
('footer_ubicacion_enlace', 'https://www.google.com/maps/search/CLINICA+POPULAR+JESUS+DE+NAZARETH+Puerto+La+Cruz'),
('footer_red_1_nombre', '📷 SaludAnz'),
('footer_red_1_enlace', 'https://instagram.com/saludanz'),
('footer_red_2_nombre', '📷 Gobernación'),
('footer_red_2_enlace', 'https://instagram.com/anzoateguigob'),
('footer_contacto_sede', 'Av. Miranda, Barcelona.'),
('footer_contacto_tel', '0281-2752482 / 0412-0572125'),
('footer_contacto_correo', 'saludanzrrhh2024@gmail.com')
ON CONFLICT (clave) DO NOTHING;

-- Nota: Para que el administrador pueda editar, deberás configurar políticas de autenticación en Supabase (RLS de UPDATE) más adelante.

-- Permisos anónimos de escritura (Solo para desarrollo)
CREATE POLICY "Permitir insercion anonima servicios" ON servicios FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualizacion anonima servicios" ON servicios FOR UPDATE USING (true);
CREATE POLICY "Permitir borrado anonimo servicios" ON servicios FOR DELETE USING (true);

-- Permisos anónimos de escritura para configuraciones (Marca Blanca)
CREATE POLICY "Permitir insercion anonima configuraciones" ON configuraciones FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualizacion anonima configuraciones" ON configuraciones FOR UPDATE USING (true);
CREATE POLICY "Permitir borrado anonimo configuraciones" ON configuraciones FOR DELETE USING (true);
